version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainer-frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - trainer-network

networks:
  trainer-network:
    external: true