version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainer-frontend
    ports:
      - "8080:80"    # ← замените 8080 на нужный вам порт
    restart: always
    networks:
      - trainer-network

networks:
  trainer-network:
    external: true